'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const core = require('./lib/battle');
const handler = require('./api/battle');

function read(file) {
  return fs.readFileSync(path.join(__dirname, file), 'utf8');
}

function humanVerse(text) {
  return { role: 'human', text: text || 'I kept the hoodie on the chair after midnight.' };
}

function turn(extra) {
  return Object.assign({
    rounds: 3,
    vibe: 'friendly',
    starter: 'human',
    topic: 'a borrowed jacket',
    name: 'Sam',
    variant: 0,
    transcript: [humanVerse()],
  }, extra || {});
}

function mockRes() {
  return {
    statusCode: 0,
    headers: {},
    body: '',
    setHeader: function (key, value) { this.headers[key] = value; },
    end: function (raw) {
      this.body = raw;
      this.json = JSON.parse(raw);
    },
  };
}

function mockReq(body, ip) {
  return {
    method: 'POST',
    headers: { 'x-forwarded-for': ip || '203.0.113.10' },
    body: body,
  };
}

async function post(body, ip) {
  const res = mockRes();
  await handler(mockReq(body, ip), res);
  return res;
}

function linesOf(text) {
  return String(text || '').split('\n').filter(Boolean);
}

function runExport() {
  const verses = [
    { role: 'human', text: 'I kept the hoodie.\nThe chair stayed warm.' },
    {
      role: 'ai',
      preview: true,
      text: 'You kept the hoodie.\nI set it back.\nWritten with Grok\nPreview mode: sample verse, not written by AI.',
    },
  ];
  const withTags = core.formatSunoLyrics(verses, { intro: true, outro: true });
  assert.ok(withTags.indexOf('[Intro]') === 0);
  assert.ok(withTags.indexOf('[Verse 1 - Human]') > 0);
  assert.ok(withTags.indexOf('[Verse 1 - Human]') < withTags.indexOf('[Verse 1 - AI]'));
  assert.ok(withTags.trim().endsWith('[Outro]'));
  assert.ok(withTags.includes('I kept the hoodie.'));
  assert.ok(withTags.includes('I set it back.'));
  assert.ok(!/written with/i.test(withTags));
  assert.ok(!/preview mode/i.test(withTags));
  assert.ok(!/grok/i.test(withTags));
  assert.ok(!/commentary/i.test(withTags));

  const plain = core.formatSunoLyrics(verses, {});
  assert.ok(!plain.includes('[Intro]'));
  assert.ok(!plain.includes('[Outro]'));
  assert.ok(plain.startsWith('[Verse 1 - Human]'));

  const aiFirst = core.formatSunoLyrics([
    { role: 'ai', text: 'Opening bar one.\nOpening bar two.\nOpening bar three.\nOpening bar four.' },
    { role: 'human', text: 'Answer one.\nAnswer two.\nAnswer three.\nAnswer four.' },
  ], {});
  assert.ok(aiFirst.indexOf('[Verse 1 - AI]') < aiFirst.indexOf('[Verse 1 - Human]'));

  const sampleCredit = core.creditSummary(verses);
  assert.ok(sampleCredit.includes('Lines you wrote: 2'));
  assert.ok(sampleCredit.includes('Sample lines, not written by AI: 2'));
  assert.ok(!/Lines generated by AI: 2/.test(sampleCredit));
  assert.ok(sampleCredit.includes(core.CREDIT_NOTE));
  assert.ok(/not legal advice/i.test(core.CREDIT_NOTE));
  assert.ok(!/copyright/i.test(core.CREDIT_NOTE));
  assert.ok(!/you own/i.test(core.CREDIT_NOTE));

  const liveCredit = core.creditSummary([
    { role: 'human', text: 'One line from me.\nAnother line from me.' },
    { role: 'ai', preview: false, text: 'One line back.\nAnother line back.' },
  ]);
  assert.ok(liveCredit.includes('Lines you wrote: 2'));
  assert.ok(liveCredit.includes('Lines generated by AI: 2'));
  assert.ok(!/Sample lines/.test(liveCredit));

  ['friendly', 'competitive', 'roast'].forEach(function (vibe) {
    const style = core.buildStylePrompt(vibe);
    assert.ok(/two contrasting voices trading verses/i.test(style.prompt));
    assert.ok(style.prompt.includes(String(style.bpm)));
    assert.ok(style.prompt.includes('BPM'));
    assert.ok(!/drake|taylor|eminem|kendrick|beyonc/i.test(style.prompt));
    assert.strictEqual(style.artistNamesStripped, false);
  });
  assert.strictEqual(core.STYLE.friendly.bpm, 94);
  assert.strictEqual(core.STYLE.competitive.bpm, 144);
  assert.strictEqual(core.STYLE.roast.bpm, 100);
  const stripped = core.cleanPrompt('two voices in the style of Drake, 90 BPM');
  assert.ok(!/drake/i.test(stripped));

  const session = core.helperSession({
    verses: [
      { role: 'human', text: 'I kept the hoodie on the chair tonight.' },
      { role: 'ai', preview: true, text: 'You kept the hoodie and I answered.' },
    ],
    topic: 'a borrowed jacket',
    name: 'Sam',
    vibe: 'friendly',
  });
  assert.strictEqual(session.source, 'battle');
  assert.strictEqual(session.pack, 'hiphop');
  assert.strictEqual(session.lyrics[0].yours, true);
  assert.strictEqual(session.lyrics[1].yours, false);
  assert.strictEqual(session.battleDraft.sections[0].label, 'Verse 1 - Human');
  assert.strictEqual(session.battleDraft.sections[1].label, 'Verse 1 - AI');
  assert.strictEqual(session.battleDraft.sections[0].lines[0].source, 'user');
  assert.strictEqual(session.battleDraft.sections[1].lines[0].source, 'generated');
}

function runBattleRules() {
  assert.ok(/only your next verse/i.test(core.SYSTEM_PROMPT));
  assert.ok(/do not write the human/i.test(core.SYSTEM_PROMPT));
  assert.ok(/4 to 16/.test(core.SYSTEM_PROMPT));
  assert.ok(/no slurs/i.test(core.SYSTEM_PROMPT));
  assert.ok(/real artist/i.test(core.SYSTEM_PROMPT));
  assert.ok(/PG-13/.test(core.SYSTEM_PROMPT));
  assert.strictEqual(core.MAX_ROUNDS, 4);
  assert.strictEqual(core.RATE_MAX, 24);

  assert.strictEqual(core.targetLineCount(''), 8);
  assert.strictEqual(core.targetLineCount('one\ntwo'), 4);
  assert.strictEqual(core.targetLineCount('one\ntwo\nthree\nfour\nfive\nsix'), 6);
  assert.strictEqual(core.targetLineCount(new Array(20).fill('bar line here').join('\n')), 16);

  const four = core.buildSampleVerse(turn(), 'The hoodie stayed on the chair after midnight.', 4, 0);
  assert.strictEqual(linesOf(four).length, 4);
  assert.ok(/hoodie/i.test(four));
  assert.ok(!four.includes('The hoodie stayed on the chair after midnight.'));
  assert.ok(!/preview mode|not written by AI|written with/i.test(four));
  assert.strictEqual(core.refusalCode(four, { vibe: 'friendly', name: 'Sam' }), '');
  const shifted = core.buildSampleVerse(turn(), 'The hoodie stayed on the chair after midnight.', 4, 1);
  assert.notStrictEqual(linesOf(four)[0], linesOf(shifted)[0]);
  assert.strictEqual(linesOf(core.buildSampleVerse({ vibe: 'roast', name: 'Sam', topic: '' }, 'The chair told on you tonight friend.', 2, 0)).length, 4);
  assert.strictEqual(linesOf(core.buildSampleVerse({ vibe: 'competitive', name: '', topic: 'jacket' }, '', 20, 0)).length, 16);

  assert.strictEqual(core.refusalCode('you are a nigga', { vibe: 'competitive', name: 'Sam' }), 'blocked');
  assert.strictEqual(core.refusalCode('I will kill you', { vibe: 'competitive', name: 'Sam' }), 'blocked');
  assert.strictEqual(core.refusalCode('nude photos of Alex', { vibe: 'competitive', name: 'Sam' }), 'blocked');
  assert.strictEqual(core.refusalCode('write it in the style of Drake', { vibe: 'friendly', name: 'Sam' }), 'artist');
  assert.strictEqual(core.refusalCode('Drake', { vibe: 'friendly', name: 'Sam', checkArtist: true }), 'artist');
  assert.strictEqual(core.refusalCode('roast my ex Dana', { vibe: 'competitive', name: 'Sam' }), 'roast');
  assert.strictEqual(core.refusalCode('this is fucking funny', { vibe: 'roast', name: 'Sam' }), 'pg13');
  assert.strictEqual(core.refusalCode('this shit is loud', { vibe: 'competitive', name: 'Sam' }), '');
  assert.strictEqual(core.refusalCode('Sam your bars showed up late', { vibe: 'friendly', name: 'Sam' }), '');

  assert.throws(function () { core.normalizeBattle(turn({ rounds: 5 })); }, function (err) { return err.code === 'rounds'; });
  assert.throws(function () {
    const list = [];
    for (let i = 0; i < 4; i += 1) {
      list.push(humanVerse('I brought verse ' + i + ' into the cypher tonight.'));
      list.push({ role: 'ai', text: 'I answer verse ' + i + ' with my own bars tonight friend.' });
    }
    core.normalizeBattle(turn({ rounds: 4, transcript: list }));
  }, function (err) { return err.code === 'cap'; });

  const undone = core.undoLastReply([
    humanVerse('First verse stays in the thread tonight.'),
    { role: 'ai', text: 'First reply stays too.' },
    humanVerse('Second verse comes back to the box tonight.'),
    { role: 'ai', text: 'Second reply goes away.' },
  ]);
  assert.strictEqual(undone.verses.length, 2);
  assert.strictEqual(undone.restored, 'Second verse comes back to the box tonight.');
  assert.strictEqual(core.exportReady([humanVerse()]), false);
  assert.strictEqual(core.exportReady([
    humanVerse(),
    { role: 'ai', text: 'A reply with enough words.' },
  ]), true);

  const cleaned = core.verseFromModel([
    'Reply one stays on the chair',
    'Reply two flips the light',
    'Reply three leaves the name',
    'Reply four keeps the count',
    'Reply five should be cut',
    'Human: I write the next verse too',
    'And I keep going',
  ].join('\n'), 4, 'I kept the hoodie on the chair\nThe midnight light stayed on', { vibe: 'friendly', name: 'Sam' });
  assert.strictEqual(cleaned.ok, true);
  assert.strictEqual(cleaned.lines.length, 4);
  assert.ok(!/human:/i.test(cleaned.text));
  assert.ok(!/next verse too/i.test(cleaned.text));
}

async function runApi() {
  const previousKey = process.env.XAI_API_KEY;
  const previousModel = process.env.XAI_MODEL;
  const originalFetch = global.fetch;
  delete process.env.XAI_API_KEY;
  let fetchCalls = 0;
  global.fetch = function () {
    fetchCalls += 1;
    return Promise.reject(new Error('fetch should not run without a key'));
  };
  try {
    const preview = await post(turn(), '203.0.113.40');
    assert.strictEqual(preview.statusCode, 200);
    assert.strictEqual(preview.json.ok, true);
    assert.strictEqual(preview.json.preview, true);
    assert.strictEqual(preview.json.source, 'sample');
    assert.strictEqual(preview.json.notice, core.PREVIEW_NOTICE);
    assert.strictEqual(preview.json.attribution, '');
    assert.strictEqual(linesOf(preview.json.verse).length, 4);
    assert.ok(/hoodie|chair|midnight/i.test(preview.json.verse));
    assert.ok(!preview.json.verse.includes(humanVerse().text));
    assert.ok(!/not written by AI/i.test(preview.json.verse));
    assert.strictEqual(fetchCalls, 0);
    assert.ok(!preview.body.includes('XAI_API_KEY'));

    const opener = await post(turn({
      starter: 'ai',
      transcript: [],
      topic: 'borrowed jacket',
    }), '203.0.113.41');
    assert.strictEqual(opener.statusCode, 200);
    assert.strictEqual(opener.json.source, 'sample');
    assert.strictEqual(linesOf(opener.json.verse).length, 8);
    assert.ok(/jacket|borrowed/i.test(opener.json.verse));
    assert.strictEqual(fetchCalls, 0);

    const slur = await post(turn({
      transcript: [humanVerse('you are a nigga and this is the verse')],
    }), '203.0.113.42');
    assert.strictEqual(slur.statusCode, 400);
    assert.ok(/slurs|line this battle/i.test(slur.json.error));
    assert.strictEqual(fetchCalls, 0);

    const artist = await post(turn({ name: 'Drake' }), '203.0.113.43');
    assert.strictEqual(artist.statusCode, 400);
    assert.ok(/artists/i.test(artist.json.error));

    const roast = await post(turn({
      vibe: 'roast',
      topic: 'roast my ex Dana',
    }), '203.0.113.44');
    assert.strictEqual(roast.statusCode, 400);
    assert.ok(/other people/i.test(roast.json.error));

    const pg = await post(turn({
      vibe: 'roast',
      transcript: [humanVerse('this is fucking funny on a clean night')],
    }), '203.0.113.45');
    assert.strictEqual(pg.statusCode, 400);
    assert.ok(/PG-13/i.test(pg.json.error));

    const rounds = await post(turn({ rounds: 5, starter: 'ai', transcript: [] }), '203.0.113.46');
    assert.strictEqual(rounds.statusCode, 400);
    assert.ok(/2, 3, or 4/.test(rounds.json.error));

    const finished = [];
    for (let i = 0; i < 4; i += 1) {
      finished.push(humanVerse('I brought verse ' + i + ' into the cypher tonight.'));
      finished.push({ role: 'ai', text: 'I answer verse ' + i + ' with my own bars tonight friend.' });
    }
    const capped = await post(turn({ rounds: 4, transcript: finished }), '203.0.113.47');
    assert.strictEqual(capped.statusCode, 400);
    assert.ok(/last round/i.test(capped.json.error));
    assert.strictEqual(fetchCalls, 0);

    const earlyCap = [];
    earlyCap.push(humanVerse('Round one from me in the cypher tonight.'));
    earlyCap.push({ role: 'ai', text: 'Round one from the reply in the cypher tonight.' });
    earlyCap.push(humanVerse('Round two from me in the cypher tonight.'));
    earlyCap.push({ role: 'ai', text: 'Round two from the reply in the cypher tonight.' });
    const twoRounds = await post(turn({ rounds: 2, transcript: earlyCap }), '203.0.113.48');
    assert.strictEqual(twoRounds.statusCode, 400);
    assert.ok(/last round/i.test(twoRounds.json.error));

    const honeyIp = '203.0.113.49';
    for (let i = 0; i < core.RATE_MAX; i += 1) handler._limiter.allow(honeyIp);
    const honey = await post(Object.assign(turn(), { company_website: 'https://spam.test' }), honeyIp);
    assert.strictEqual(honey.statusCode, 400);
    const blocked = await post(turn(), honeyIp);
    assert.strictEqual(blocked.statusCode, 429);
    assert.ok(/wait/i.test(blocked.json.error));
    assert.strictEqual(fetchCalls, 0);

    const long = await post(turn({ topic: 'y'.repeat(core.TOPIC_MAX + 1) }), '203.0.113.50');
    assert.strictEqual(long.statusCode, 400);
    assert.ok(/shorten/i.test(long.json.error));

    const huge = mockRes();
    await handler({
      method: 'POST',
      headers: { 'x-forwarded-for': '203.0.113.51' },
      body: 'x'.repeat(core.BODY_MAX + 1),
    }, huge);
    assert.strictEqual(huge.statusCode, 413);

    const get = mockRes();
    await handler({ method: 'GET', headers: {}, body: {} }, get);
    assert.strictEqual(get.statusCode, 405);

    process.env.XAI_API_KEY = 'test-key-not-real';
    process.env.XAI_MODEL = 'grok-4.3';
    let sent;
    const modelVerse = [
      'Reply one stays on the chair',
      'Reply two flips the light',
      'Reply three leaves the name',
      'Reply four keeps the count',
      'Human: I write the next verse too',
    ].join('\n');
    global.fetch = function (url, opts) {
      fetchCalls += 1;
      sent = { url: url, opts: opts };
      return Promise.resolve({
        ok: true,
        json: async function () {
          return { choices: [{ message: { content: modelVerse } }] };
        },
      });
    };
    const live = await post(turn({
      transcript: [humanVerse('I kept the hoodie on the chair\nThe midnight light stayed on\nI did not text you first\nThe room can keep your name')],
    }), '203.0.113.52');
    assert.strictEqual(live.statusCode, 200);
    assert.strictEqual(live.json.preview, false);
    assert.strictEqual(live.json.source, 'grok');
    assert.strictEqual(live.json.notice, '');
    assert.strictEqual(live.json.attribution, core.ATTRIBUTION);
    assert.strictEqual(linesOf(live.json.verse).length, 4);
    assert.ok(!/human:/i.test(live.json.verse));
    assert.ok(!/next verse too/i.test(live.json.verse));
    assert.strictEqual(sent.url, 'https://api.x.ai/v1/chat/completions');
    const payload = JSON.parse(sent.opts.body);
    assert.strictEqual(payload.model, 'grok-4.3');
    assert.strictEqual(payload.reasoning_effort, 'none');
    assert.ok(/only your next verse/i.test(payload.messages[0].content));
    assert.ok(/do not write the human/i.test(payload.messages[1].content));
    assert.ok(payload.messages[1].content.includes('hoodie'));
    assert.strictEqual(sent.opts.headers.Authorization, 'Bearer test-key-not-real');
    assert.ok(!live.body.includes('test-key-not-real'));
    assert.strictEqual(fetchCalls, 1);

    process.env.XAI_MODEL = 'grok-4.20-0309-non-reasoning';
    await post(turn(), '203.0.113.53');
    const nonReason = JSON.parse(sent.opts.body);
    assert.strictEqual(nonReason.model, 'grok-4.20-0309-non-reasoning');
    assert.strictEqual(nonReason.reasoning_effort, undefined);
  } finally {
    global.fetch = originalFetch;
    if (previousKey === undefined) delete process.env.XAI_API_KEY;
    else process.env.XAI_API_KEY = previousKey;
    if (previousModel === undefined) delete process.env.XAI_MODEL;
    else process.env.XAI_MODEL = previousModel;
  }
}

function runPage() {
  const html = read('battle.html');
  const js = read('battle.js');
  const api = read('api/battle.js');
  const index = read('index.html');
  const vercel = JSON.parse(read('vercel.json'));
  const nav = html.match(/<nav class="nav-links"[\s\S]*?<\/nav>/)[0];
  const footer = html.match(/<footer[\s\S]*?<\/footer>/)[0];
  const intro = html.match(/<p class="sh-intro">[\s\S]*?<\/p>/)[0];

  assert.ok(html.includes('Trade verses'));
  assert.ok(html.includes('You must be 18+ to use this page.'));
  assert.ok(html.includes('noindex'));
  assert.ok(html.includes('name="company_website"'));
  assert.ok(html.includes('Friendly cypher'));
  assert.ok(html.includes('Competitive'));
  assert.ok(html.includes('Clean roast'));
  assert.ok(html.includes('data-value="2"'));
  assert.ok(html.includes('data-value="3"'));
  assert.ok(html.includes('data-value="4"'));
  assert.ok(html.includes('Who starts'));
  assert.ok(html.includes('>Human<'));
  assert.ok(html.includes('>AI<'));
  assert.ok(html.includes('id="bt-undo"'));
  assert.ok(html.includes('>Undo<'));
  assert.ok(html.includes('id="bt-regen"'));
  assert.ok(html.includes('>Regenerate<'));
  assert.ok(html.includes('id="bt-verse"'));
  assert.ok(html.includes('Copy for Suno'));
  assert.ok(html.includes('id="bt-intro"'));
  assert.ok(html.includes('id="bt-outro"'));
  assert.ok(html.includes('Style prompt for Suno'));
  assert.ok(html.includes(core.CREDIT_NOTE));
  assert.ok(html.includes('href="/song-helper?from=battle"'));
  assert.ok(html.includes('href="/cover-art"'));
  assert.ok(html.includes('No slurs, hate, threats'));
  assert.ok(html.includes('Clean roast stays PG-13.'));
  assert.ok(!/\$/.test(intro));
  assert.ok(!/distribution/i.test(intro));
  assert.ok(!/first ever|guaranteed|checked by people/i.test(html + js));
  assert.ok(!/Grok/.test(html), 'Grok stays off the page chrome');
  assert.ok(!/Powered by Grok/i.test(html + js));
  assert.ok(!html.includes('XAI_API_KEY') && !js.includes('XAI_API_KEY'));
  assert.ok(!html.includes('api.x.ai') && !js.includes('api.x.ai'));
  assert.ok(js.includes('/api/battle'));
  assert.ok(js.includes('formatSunoLyrics'));
  assert.ok(js.includes('creditCounts'));
  assert.ok(js.includes('undoLastReply'));
  assert.ok(js.includes('helperSession'));
  assert.ok(js.includes('core.PREVIEW_NOTICE') || js.includes('data.notice'));
  assert.ok(!/battle/i.test(nav), 'the battle page nav does not link to itself');
  assert.ok(!/battle/i.test(footer));
  assert.ok(!index.includes('/battle'));
  assert.ok(!index.includes('battle.html'));
  assert.ok((vercel.rewrites || []).some(function (row) {
    return row.source === '/battle' && row.destination === '/battle.html';
  }));
  assert.ok(api.includes('XAI_API_KEY'));
  assert.ok(api.includes('https://api.x.ai/v1/chat/completions'));
  assert.ok(api.includes('Cloudflare Turnstile'));
  assert.ok(/in-memory/i.test(api));
  assert.ok(api.includes('core.RATE_MAX'));
  assert.ok(api.includes('normalizeBattle'));

  fs.readdirSync(__dirname).filter(function (name) { return name.endsWith('.html'); }).forEach(function (file) {
    if (file === 'battle.html') return;
    const page = read(file);
    assert.ok(!page.includes('href="/battle"') && !page.includes('href="/battle/') && !page.includes('battle.html'), file + ' must not link the battle page');
  });
  fs.readdirSync(__dirname).forEach(function (name) {
    if (!/sitemap/i.test(name)) return;
    assert.ok(!read(name).includes('battle'), name + ' must not list the battle page');
  });
  ['song-helper.html', 'cover-art.html', 'index.html', 'faq.html', 'about.html'].forEach(function (file) {
    const page = read(file);
    const pageNav = page.match(/<nav class="nav-links"[\s\S]*?<\/nav>/);
    const pageFooter = page.match(/<footer[\s\S]*?<\/footer>/);
    const chunk = (pageNav ? pageNav[0] : '') + (pageFooter ? pageFooter[0] : '');
    assert.ok(!chunk.includes('/battle') && !chunk.includes('battle.html'), file + ' nav and footer stay clear of battle');
  });
  const helperJs = read('song-helper.js');
  assert.ok(helperJs.includes("params.get('from') !== 'battle'"));
  assert.ok(helperJs.includes('battleDraft'));
  assert.ok(helperJs.includes('else showStep();'));
}

async function run() {
  runExport();
  runBattleRules();
  await runApi();
  runPage();
  console.log('battle.test.js ok');
}

run().catch(function (err) {
  console.error(err);
  process.exit(1);
});
