'use strict';

/**
 * Reference lists for the upload form.
 *
 * Languages: ISO 639-1 codes. ToneGrid track/release language is ISO 639-1
 * (api-docs.tonegrid.pro + OpenAPI). There is no GET /languages on ToneGrid.
 *
 * Genres: ToneGrid has no GET /genres (404). POST /releases takes a free-text
 * `genre` string (example Afrobeats). Subgenre is returned on GET release but
 * is not in the POST /releases body or OpenAPI example, so we do not send it.
 * This catalogue is the complete iTunes/DSP music genre tree plus Afrobeats,
 * not a custom 7-item shortlist.
 *
 * Stores: official ToneGrid slugs from POST /releases/:uuid/dsps docs/OpenAPI.
 * Live list: GET /supply-chain/dsps. YouTube Music slug: youtube-music.
 */

const LANGUAGES = [
  { code: "aa", name: "Afar" },
  { code: "ab", name: "Abkhazian" },
  { code: "ae", name: "Avestan" },
  { code: "af", name: "Afrikaans" },
  { code: "ak", name: "Akan" },
  { code: "am", name: "Amharic" },
  { code: "an", name: "Aragonese" },
  { code: "ar", name: "Arabic" },
  { code: "as", name: "Assamese" },
  { code: "av", name: "Avaric" },
  { code: "ay", name: "Aymara" },
  { code: "az", name: "Azerbaijani" },
  { code: "ba", name: "Bashkir" },
  { code: "be", name: "Belarusian" },
  { code: "bg", name: "Bulgarian" },
  { code: "bi", name: "Bislama" },
  { code: "bm", name: "Bambara" },
  { code: "bn", name: "Bengali" },
  { code: "bo", name: "Tibetan" },
  { code: "br", name: "Breton" },
  { code: "bs", name: "Bosnian" },
  { code: "ca", name: "Catalan" },
  { code: "ce", name: "Chechen" },
  { code: "ch", name: "Chamorro" },
  { code: "co", name: "Corsican" },
  { code: "cr", name: "Cree" },
  { code: "cs", name: "Czech" },
  { code: "cu", name: "Church Slavic" },
  { code: "cv", name: "Chuvash" },
  { code: "cy", name: "Welsh" },
  { code: "da", name: "Danish" },
  { code: "de", name: "German" },
  { code: "dv", name: "Divehi" },
  { code: "dz", name: "Dzongkha" },
  { code: "ee", name: "Ewe" },
  { code: "el", name: "Greek" },
  { code: "en", name: "English" },
  { code: "eo", name: "Esperanto" },
  { code: "es", name: "Spanish" },
  { code: "et", name: "Estonian" },
  { code: "eu", name: "Basque" },
  { code: "fa", name: "Persian" },
  { code: "ff", name: "Fulah" },
  { code: "fi", name: "Finnish" },
  { code: "fj", name: "Fijian" },
  { code: "fo", name: "Faroese" },
  { code: "fr", name: "French" },
  { code: "fy", name: "Western Frisian" },
  { code: "ga", name: "Irish" },
  { code: "gd", name: "Scottish Gaelic" },
  { code: "gl", name: "Galician" },
  { code: "gn", name: "Guarani" },
  { code: "gu", name: "Gujarati" },
  { code: "gv", name: "Manx" },
  { code: "ha", name: "Hausa" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "ho", name: "Hiri Motu" },
  { code: "hr", name: "Croatian" },
  { code: "ht", name: "Haitian Creole" },
  { code: "hu", name: "Hungarian" },
  { code: "hy", name: "Armenian" },
  { code: "hz", name: "Herero" },
  { code: "ia", name: "Interlingua" },
  { code: "id", name: "Indonesian" },
  { code: "ie", name: "Interlingue" },
  { code: "ig", name: "Igbo" },
  { code: "ii", name: "Sichuan Yi" },
  { code: "ik", name: "Inupiaq" },
  { code: "io", name: "Ido" },
  { code: "is", name: "Icelandic" },
  { code: "it", name: "Italian" },
  { code: "iu", name: "Inuktitut" },
  { code: "ja", name: "Japanese" },
  { code: "jv", name: "Javanese" },
  { code: "ka", name: "Georgian" },
  { code: "kg", name: "Kongo" },
  { code: "ki", name: "Kikuyu" },
  { code: "kj", name: "Kuanyama" },
  { code: "kk", name: "Kazakh" },
  { code: "kl", name: "Kalaallisut" },
  { code: "km", name: "Khmer" },
  { code: "kn", name: "Kannada" },
  { code: "ko", name: "Korean" },
  { code: "kr", name: "Kanuri" },
  { code: "ks", name: "Kashmiri" },
  { code: "ku", name: "Kurdish" },
  { code: "kv", name: "Komi" },
  { code: "kw", name: "Cornish" },
  { code: "ky", name: "Kyrgyz" },
  { code: "la", name: "Latin" },
  { code: "lb", name: "Luxembourgish" },
  { code: "lg", name: "Ganda" },
  { code: "li", name: "Limburgan" },
  { code: "ln", name: "Lingala" },
  { code: "lo", name: "Lao" },
  { code: "lt", name: "Lithuanian" },
  { code: "lu", name: "Luba-Katanga" },
  { code: "lv", name: "Latvian" },
  { code: "mg", name: "Malagasy" },
  { code: "mh", name: "Marshallese" },
  { code: "mi", name: "Maori" },
  { code: "mk", name: "Macedonian" },
  { code: "ml", name: "Malayalam" },
  { code: "mn", name: "Mongolian" },
  { code: "mr", name: "Marathi" },
  { code: "ms", name: "Malay" },
  { code: "mt", name: "Maltese" },
  { code: "my", name: "Burmese" },
  { code: "na", name: "Nauru" },
  { code: "nb", name: "Norwegian Bokmål" },
  { code: "nd", name: "North Ndebele" },
  { code: "ne", name: "Nepali" },
  { code: "ng", name: "Ndonga" },
  { code: "nl", name: "Dutch" },
  { code: "nn", name: "Norwegian Nynorsk" },
  { code: "no", name: "Norwegian" },
  { code: "nr", name: "South Ndebele" },
  { code: "nv", name: "Navajo" },
  { code: "ny", name: "Chichewa" },
  { code: "oc", name: "Occitan" },
  { code: "oj", name: "Ojibwa" },
  { code: "om", name: "Oromo" },
  { code: "or", name: "Odia" },
  { code: "os", name: "Ossetian" },
  { code: "pa", name: "Punjabi" },
  { code: "pi", name: "Pali" },
  { code: "pl", name: "Polish" },
  { code: "ps", name: "Pashto" },
  { code: "pt", name: "Portuguese" },
  { code: "qu", name: "Quechua" },
  { code: "rm", name: "Romansh" },
  { code: "rn", name: "Rundi" },
  { code: "ro", name: "Romanian" },
  { code: "ru", name: "Russian" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "sa", name: "Sanskrit" },
  { code: "sc", name: "Sardinian" },
  { code: "sd", name: "Sindhi" },
  { code: "se", name: "Northern Sami" },
  { code: "sg", name: "Sango" },
  { code: "si", name: "Sinhala" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "sm", name: "Samoan" },
  { code: "sn", name: "Shona" },
  { code: "so", name: "Somali" },
  { code: "sq", name: "Albanian" },
  { code: "sr", name: "Serbian" },
  { code: "ss", name: "Swati" },
  { code: "st", name: "Southern Sotho" },
  { code: "su", name: "Sundanese" },
  { code: "sv", name: "Swedish" },
  { code: "sw", name: "Swahili" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "tg", name: "Tajik" },
  { code: "th", name: "Thai" },
  { code: "ti", name: "Tigrinya" },
  { code: "tk", name: "Turkmen" },
  { code: "tl", name: "Tagalog" },
  { code: "tn", name: "Tswana" },
  { code: "to", name: "Tonga" },
  { code: "tr", name: "Turkish" },
  { code: "ts", name: "Tsonga" },
  { code: "tt", name: "Tatar" },
  { code: "tw", name: "Twi" },
  { code: "ty", name: "Tahitian" },
  { code: "ug", name: "Uyghur" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "uz", name: "Uzbek" },
  { code: "ve", name: "Venda" },
  { code: "vi", name: "Vietnamese" },
  { code: "vo", name: "Volapük" },
  { code: "wa", name: "Walloon" },
  { code: "wo", name: "Wolof" },
  { code: "xh", name: "Xhosa" },
  { code: "yi", name: "Yiddish" },
  { code: "yo", name: "Yoruba" },
  { code: "za", name: "Zhuang" },
  { code: "zh", name: "Chinese" },
  { code: "zu", name: "Zulu" },
];

const GENRES = [
  "21st Century",
  "Acoustic Blues",
  "Adult Alternative",
  "Adult Contemporary",
  "African",
  "African Dancehall",
  "African Reggae",
  "Afrikaans",
  "Afro House",
  "Afro Soul",
  "Afro-Beat",
  "Afro-folk",
  "Afro-fusion",
  "Afro-Pop",
  "Afrobeats",
  "Air de Cours",
  "Alte",
  "Alternative",
  "Alternative Country",
  "Alternative Folk",
  "Alternative Rap",
  "Amapiano",
  "Ambient",
  "American Trad Rock",
  "Americana",
  "Anime",
  "Arabesque",
  "Arabic",
  "Arabic Pop",
  "Arena Rock",
  "Ars Antiqua",
  "Ars Nova",
  "Art Song",
  "Asia",
  "Assamese",
  "Australia",
  "Avant-Garde",
  "Avant-Garde Jazz",
  "Axé",
  "Baile Funk",
  "Baladas y Boleros",
  "Ballet",
  "Bard in Russian",
  "Baroque",
  "Baroque Era",
  "Bass",
  "Bel Canto",
  "Benga",
  "Bengali",
  "Bhojpuri",
  "Big Band",
  "Bluegrass",
  "Blues",
  "Blues-Rock",
  "Bolero",
  "Bollywood",
  "Bongo-Flava",
  "Bop",
  "Bossa Nova",
  "Brass & Woodwinds",
  "Brazilian",
  "Breakbeat",
  "British Invasion",
  "Britpop",
  "C-Pop",
  "Cajun",
  "Calypso",
  "Cantata",
  "Cantopop/HK-Pop",
  "Caribbean",
  "Carnatic Classical",
  "Carol",
  "CCM",
  "Cello",
  "Celtic",
  "Celtic Folk",
  "Chachacha",
  "Chamber Music",
  "Chanson",
  "Chanson in Russian",
  "Chant",
  "Chanukah",
  "Chicago Blues",
  "Children's Music",
  "Chimurenga",
  "Chinese",
  "Chinese Alt",
  "Chinese Classical",
  "Chinese Flute",
  "Chinese Hip-Hop",
  "Chinese Opera",
  "Chinese Orchestral",
  "Chinese Regional Folk",
  "Chinese Rock",
  "Chinese Strings",
  "Choral",
  "Choro",
  "Christian",
  "Christian Metal",
  "Christian Pop",
  "Christian Rap",
  "Christian Rock",
  "Christmas",
  "Christmas: Children's",
  "Christmas: Classic",
  "Christmas: Classical",
  "Christmas: Country",
  "Christmas: Jazz",
  "Christmas: Modern",
  "Christmas: Pop",
  "Christmas: R&B",
  "Christmas: Religious",
  "Christmas: Rock",
  "Classic Blues",
  "Classic Christian",
  "Classical",
  "Classical Crossover",
  "College Rock",
  "Comedy",
  "Concert Aria",
  "Concerto",
  "Concerto Grosso",
  "Contemporary Bluegrass",
  "Contemporary Blues",
  "Contemporary Celtic",
  "Contemporary Country",
  "Contemporary Era",
  "Contemporary Folk",
  "Contemporary Gospel",
  "Contemporary Jazz",
  "Contemporary Latin",
  "Contemporary R&B",
  "Contemporary Singer/Songwriter",
  "Cool Jazz",
  "Country",
  "Country Blues",
  "Country Gospel",
  "Country Hip-Hop/Rap",
  "Coupé-Décalé",
  "Crossover Jazz",
  "Cuban",
  "Dabke",
  "Dance",
  "Dangdut",
  "Death Metal/Black Metal",
  "Delta Blues",
  "Deutschpop",
  "Deutschrap",
  "Devotional & Spiritual",
  "Dini",
  "Dirty South",
  "Disco",
  "Disney",
  "Dixieland",
  "Dodecaphony",
  "Doo Wop",
  "Downtempo",
  "Drinking Songs",
  "Dub",
  "Dubstep",
  "Early 20th Century",
  "Early Music",
  "Early Romantic",
  "East Coast Rap",
  "Easter",
  "Easy Listening",
  "Eclecticism",
  "Egyptian Hip-Hop",
  "Egyptian Pop",
  "Egyptian Tarab",
  "Electric Blues",
  "Electro-Cha'abi",
  "Electroacoustic",
  "Electronic",
  "Electronica",
  "EMO",
  "English Ayre",
  "Enka",
  "Environmental",
  "Ethio Jazz",
  "Europe",
  "Exercise",
  "Experimental Classical",
  "Expressionism",
  "Fado",
  "Fantasy",
  "Fantezi",
  "Farsi",
  "Film Music",
  "First Viennese School",
  "Fitness & Workout",
  "Flamenco",
  "Folk",
  "Folk-Rock",
  "Foreign Cinema",
  "Forró",
  "France",
  "French Baroque",
  "French Pop",
  "Frevo",
  "Fuji",
  "Funk",
  "Fusion",
  "Gangsta Rap",
  "Garage",
  "Genge",
  "German Folk",
  "German Pop",
  "Ghanaian Drill",
  "Ghazals",
  "Glam Rock",
  "Gospel",
  "Goth Rock",
  "Gqom",
  "Gregorian Chant",
  "Grunge",
  "Guajira",
  "Guaracha",
  "Guitar",
  "Gujarati",
  "Hair Metal",
  "Halk",
  "Halloween",
  "Hard Bop",
  "Hard Rock",
  "Hardcore",
  "Hardcore Rap",
  "Haryanvi",
  "Hawaii",
  "Healing",
  "High Classical",
  "Highlife",
  "Hindustani Classical",
  "Hip-Hop",
  "Hip-Hop in Russian",
  "Hip-Hop/Rap",
  "Holiday",
  "Holiday: Other",
  "Honky Tonk",
  "House",
  "Hörspiele",
  "Iberia",
  "IDM/Experimental",
  "Impressionism",
  "Impressionist",
  "Indian",
  "Indian Classical",
  "Indian Folk",
  "Indian Pop",
  "Indie Egyptian",
  "Indie Levant",
  "Indie Maghreb",
  "Indie Pop",
  "Indie Rock",
  "Indo Pop",
  "Indonesian Religious",
  "Industrial",
  "Inspirational",
  "Instrumental",
  "Iraqi Folk",
  "Iraqi Pop",
  "Iraqi Tarab",
  "Islamic",
  "Israeli",
  "J-Pop",
  "Jam Bands",
  "Japan",
  "Japanese Pop",
  "Jazz",
  "Jewish Holidays",
  "Jewish Music",
  "Jungle/Drum'n'bass",
  "K-Pop",
  "Kannada",
  "Karaoke",
  "Kayokyoku",
  "Khaleeji",
  "Khaleeji Folk",
  "Khaleeji Hip-Hop",
  "Khaleeji Jalsat",
  "Khaleeji Pop",
  "Khaleeji Shailat",
  "Khaleeji Tarab",
  "Kizomba",
  "Klezmer",
  "Korean",
  "Korean Classical",
  "Korean Folk-Pop",
  "Korean Hip-Hop",
  "Korean Indie",
  "Korean Rock",
  "Korean Trad Instrumental",
  "Korean Trad Song",
  "Korean Trad Theater",
  "Kuduro",
  "Kwaito",
  "Kwassa",
  "Late 20th Century",
  "Late Romantic",
  "Latin",
  "Latin Jazz",
  "Latin Rap",
  "Levant",
  "Levant Electronic",
  "Levant Hip-Hop",
  "Levant Pop",
  "Lied",
  "Lounge",
  "Lovers Rock",
  "Lullabies",
  "Maghreb Dance",
  "Maghreb Electronic",
  "Maghreb Hip-Hop",
  "Maghreb Pop",
  "Maghreb Rai",
  "Mainstream Jazz",
  "Malayalam",
  "Malaysian Pop",
  "Mambo",
  "Mandopop",
  "Manilla Sound",
  "Mapouka",
  "Marathi",
  "Marching",
  "Maskandi",
  "Mass",
  "Mbalax",
  "Medieval",
  "Medieval Era",
  "Meditation",
  "Meistergesang",
  "Metal",
  "Minimalism",
  "Minnesang",
  "Modern Dancehall",
  "Modern Era",
  "Modernism",
  "Motown",
  "MPB",
  "Music Theatre",
  "Musicals",
  "Musique concrète",
  "Música Mexicana",
  "Música tropical",
  "Nationalism",
  "Nature",
  "Ndombolo",
  "Neo-Soul",
  "Neoclassicism",
  "New Acoustic",
  "New Age",
  "New Complexity",
  "New Simplicity",
  "New Wave",
  "Nocturne",
  "North African",
  "North America",
  "Novelty",
  "Odia",
  "Old School Rap",
  "Oldies",
  "Opera",
  "Oratorio",
  "Orchestral",
  "Original Pilipino Music",
  "Original Score",
  "Outlaw Country",
  "Pagode",
  "Passion",
  "Percussion",
  "Piano",
  "Pinoy Pop",
  "Polka",
  "Polyphony",
  "Polystylism",
  "Pop",
  "Pop in Russian",
  "Pop Latino",
  "Pop Punk",
  "Pop/Rock",
  "Post-modernism",
  "PostMinimalism",
  "Praise & Worship",
  "Prima Pratica",
  "Prog-Rock/Art Rock",
  "Psychedelic",
  "Punjabi",
  "Punjabi Pop",
  "Punk",
  "Quiet Storm",
  "R&B/Soul",
  "Rabindra Sangeet",
  "Ragtime",
  "Rajasthani",
  "Rap",
  "Raíces",
  "Reggae",
  "Regional Indian",
  "Relaxation",
  "Religious",
  "Renaissance",
  "Rock",
  "Rock & Roll",
  "Rock in Russian",
  "Rock y Alternativo",
  "Rockabilly",
  "Romance in Russian",
  "Romantic",
  "Romantic Era",
  "Roots Reggae",
  "Roots Rock",
  "Russian",
  "Sacred",
  "Samba",
  "Sanat",
  "Second Viennese School",
  "Seconda Pratica",
  "Serialism",
  "Sertanejo",
  "Shangaan Electro",
  "Shows",
  "Sing-Along",
  "Singer/Songwriter",
  "Ska",
  "Smooth Jazz",
  "Soca",
  "Soft Rock",
  "Solo Instrumental",
  "Son",
  "Sonata",
  "Soukous",
  "Soul",
  "Sound Effects",
  "Soundtrack",
  "South Africa",
  "South African Hip-Hop",
  "South America",
  "Southern Gospel",
  "Southern Rock",
  "Spectral Music",
  "Spoken Word",
  "Stage Works",
  "Standards",
  "Standup Comedy",
  "Stories",
  "String Quartet",
  "Sufi",
  "Surf",
  "Swing",
  "Symphony",
  "T-Pop",
  "Taarab",
  "Tai-Pop",
  "Taiwanese Folk",
  "Tamil",
  "Tango",
  "Tarab",
  "Techno",
  "Teen Pop",
  "Telugu",
  "Tex-Mex",
  "Thai Country",
  "Thai Pop",
  "Thanksgiving",
  "Tibetan Native Music",
  "Timba",
  "Tone Poem",
  "Trad Jazz",
  "Traditional Bluegrass",
  "Traditional Celtic",
  "Traditional Country",
  "Traditional Folk",
  "Traditional Gospel",
  "Traditional Pop",
  "Trance",
  "Travel",
  "Tribute",
  "Trot",
  "Troubadour Music",
  "Trouvère Music",
  "Turkish",
  "Turkish Alternative",
  "Turkish Hip-Hop/Rap",
  "Turkish Pop",
  "Turkish Rock",
  "TV Soundtrack",
  "UK Hip-Hop",
  "Underground Rap",
  "Urban Cowboy",
  "Urbano latino",
  "Urdu",
  "Video Game",
  "Violin",
  "Vocal",
  "Vocal Jazz",
  "Vocal Music",
  "Vocal Pop",
  "Wedding Music",
  "West Coast Rap",
  "Worldbeat",
  "Worldwide",
  "Yoga",
  "Zouglou",
  "Zydeco",
  "Özgün",
];

const DOC_STORES = [
  { slug: "spotify", name: "Spotify" },
  { slug: "apple-music", name: "Apple Music" },
  { slug: "youtube-music", name: "YouTube Music" },
  { slug: "amazon-music", name: "Amazon Music" },
  { slug: "deezer", name: "Deezer" },
  { slug: "tidal", name: "Tidal" },
  { slug: "soundcloud", name: "SoundCloud" },
  { slug: "boomplay", name: "Boomplay" },
  { slug: "audiomack", name: "Audiomack" },
  { slug: "pandora", name: "Pandora" },
  { slug: "napster", name: "Napster" },
  { slug: "anghami", name: "Anghami" },
  { slug: "tiktok", name: "TikTok" },
  { slug: "tiktok-music", name: "TikTok Music" },
  { slug: "iheartradio", name: "iHeartRadio" },
  { slug: "kkbox", name: "KKBOX" },
  { slug: "jiosaavn", name: "JioSaavn" },
  { slug: "youtube", name: "YouTube" },
];

const YOUTUBE_MUSIC_SLUG = 'youtube-music';
const YOUTUBE_MUSIC_SLUGS = new Set(['youtube-music', 'youtubemusic', 'youtube_music']);


function asList(payload) {
  if (Array.isArray(payload)) return payload;
  if (!payload || typeof payload !== 'object') return [];
  if (Array.isArray(payload.dsps)) return payload.dsps;
  if (payload.data && Array.isArray(payload.data.dsps)) return payload.data.dsps;
  if (Array.isArray(payload.data)) return payload.data;
  if (payload.data && Array.isArray(payload.data.data)) return payload.data.data;
  return [];
}

function storeName(row, slug) {
  const raw = row && (row.name || row.dsp_name || row.title || row.label);
  if (typeof raw === 'string' && raw.trim()) return raw.trim();
  if (/youtube/i.test(slug) && /music/i.test(slug)) return 'YouTube Music';
  return slug
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function normalizeStoreSlug(value) {
  const slug = String(value || '').trim().toLowerCase();
  if (!slug) return '';
  if (!/^[a-z0-9][a-z0-9_-]{0,63}$/.test(slug)) return '';
  return slug;
}

function isYouTubeMusicStore(row) {
  const slug = normalizeStoreSlug(row && (row.slug || row.dsp || row.id));
  if (YOUTUBE_MUSIC_SLUGS.has(slug)) return true;
  const name = String((row && (row.name || row.dsp_name)) || '').trim();
  return /^youtube\s*music$/i.test(name);
}

function youtubeMusicSlug(stores) {
  const list = Array.isArray(stores) ? stores : [];
  for (let i = 0; i < list.length; i += 1) {
    if (isYouTubeMusicStore(list[i])) {
      return normalizeStoreSlug(list[i].slug || list[i].dsp || list[i].id) || YOUTUBE_MUSIC_SLUG;
    }
  }
  return '';
}

function parseStores(payload) {
  const seen = new Set();
  const out = [];
  asList(payload).forEach((row) => {
    const slug = normalizeStoreSlug(
      typeof row === 'string' ? row : (row && (row.slug || row.dsp || row.id))
    );
    if (!slug || seen.has(slug)) return;
    seen.add(slug);
    out.push({
      slug,
      name: typeof row === 'string' ? storeName({}, slug) : storeName(row, slug),
    });
  });
  return out;
}

function documentedStores() {
  return DOC_STORES.map((row) => ({ slug: row.slug, name: row.name }));
}

function languagePayload() {
  return {
    source: 'iso-639-1',
    languages: LANGUAGES.map((row) => ({ code: row.code, name: row.name })),
  };
}

function genrePayload() {
  return {
    source: 'dsp-catalog',
    subgenre: false,
    genres: GENRES.slice(),
  };
}

function normalizeLanguage(value) {
  const raw = String(value || '').trim();
  if (!raw) return '';
  const lower = raw.toLowerCase();
  const byCode = LANGUAGES.find((row) => row.code === lower);
  if (byCode) return byCode.code;
  const byName = LANGUAGES.find((row) => row.name.toLowerCase() === lower);
  if (byName) return byName.name === raw ? byName.code : byName.code;
  if (/^[a-z]{2}$/i.test(raw)) return lower;
  return null;
}

function requestedStores(body) {
  const raw = body && (body.stores || body.dsps);
  if (raw == null) return null;
  if (!Array.isArray(raw)) return [];
  const seen = new Set();
  const out = [];
  raw.forEach((value) => {
    const slug = normalizeStoreSlug(typeof value === 'string' ? value : value && (value.slug || value.dsp));
    if (!slug || seen.has(slug)) return;
    seen.add(slug);
    out.push(slug);
  });
  return out;
}

function withYouTubeMusic(slugs, available) {
  const list = Array.isArray(slugs) ? slugs.slice() : [];
  const yt = youtubeMusicSlug(available) || YOUTUBE_MUSIC_SLUG;
  const hasYt = list.some((slug) => YOUTUBE_MUSIC_SLUGS.has(slug) || slug === yt);
  if (!hasYt && yt) list.push(yt);
  return list;
}

module.exports = {
  DOC_STORES,
  GENRES,
  LANGUAGES,
  YOUTUBE_MUSIC_SLUG,
  documentedStores,
  genrePayload,
  isYouTubeMusicStore,
  languagePayload,
  normalizeLanguage,
  normalizeStoreSlug,
  parseStores,
  requestedStores,
  withYouTubeMusic,
  youtubeMusicSlug,
};
